# Generated by Django 4.2.6 on 2023-10-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('firstChoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firstChoice', to='mypolls.pollchoice')),
                ('secondChoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondChoice', to='mypolls.pollchoice')),
            ],
        ),
    ]
